### ISSUE TITLE
questcache.wdb System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by SergGrey** [MMOSimca/SaneWDBReader#1]
Hello, an error "System.ArgumentOutOfRangeException" occurs when working with "questcache.wdb". The error occurs at the moment "QuestCache.cs:351(condText.PlayerConditionID = ds.GetInt();)".  I guess the structure has changed in the new version or I just have crooked hands. Help please, I want to try to use your program to get the translation of the game and transfer it to the addon for translation.

**Comment by MMOSimca** [comment]
Ah, yes. I think there are actually two structure changes since 10.0 that I haven't added yet. I'll try to do that tonight.

**Comment by MMOSimca** [comment]
Fixed in https://github.com/MMOSimca/SaneWDBReader/commit/5aaef5e1e07aa8afa23af13ccb8d89953a7d3d78.

Newest version of the program on the Retail branch should work fine for 10.1.7 and 10.2.0.
